title: Hakan Melikoglu
description: iOS Developer & Technology Enthusiast
url: "https://hakanmelikoglu.github.io"
baseurl: ""

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - projects.md
  - blog.md
  - support.md
  - privacy-policy.md

# Author info
author:
  name: Hakan Melikoglu
  email: exiframe@hakanmelikoglu.com
  
# Social links
github_username: hakanmelikoglu
linkedin_username: hakanmelikoglu